version: '2'
services:
  workspace:
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    image: mhart/alpine-node:10.4.0
    tty: true
    ports:
      - 3000:3000
    env_file:
      - .env
